ollama:
  model: "gemma3:12b-it-qat"
  temperature: 0.7
  max_tokens: 512

vector_db:
  path: "./data/vector_db"

memory:
  enable_contextual_memory: true
  memory_limit: 100  # Number of interactions to store

firebase:
  config_path: "./firebase/firebase_config.json"

